=== stacks-network/stacks-core/docs/rpc/api/core-node/get-contract-interface.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "GET request to get contract interface",
  "title": "ContractInterfaceResponse",
  "type": "object",
  "required": ["functions", "variables", "maps", "fungible_tokens", "non_fungible_tokens"],
  "properties": {
    "functions": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "List of defined methods"
    },
    "variables": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "List of defined variables"
    },
    "maps": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "List of defined data-maps"
    },
    "fungible_tokens": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "List of fungible tokens in the contract"
    },
    "non_fungible_tokens": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "List of non-fungible tokens in the contract"
    }
  }
}

=== stacks-network/stacks-core/docs/rpc/api/core-node/get-contract-interface.example.json
{
  "functions": [
    {
      "name": "get-value",
      "access": "public",
      "args": [
        {
          "name": "key",
          "type": {
            "buffer": {
              "length": 32
            }
          }
        }
      ],
      "outputs": {
        "type": {
          "response": {
            "ok": {
              "buffer": {
                "length": 32
              }
            },
            "error": "int128"
          }
        }
      }
    },
    {
      "name": "set-value",
      "access": "public",
      "args": [
        {
          "name": "key",
          "type": {
            "buffer": {
              "length": 32
            }
          }
        },
        {
          "name": "value",
          "type": {
            "buffer": {
              "length": 32
            }
          }
        }
      ],
      "outputs": {
        "type": {
          "response": {
            "ok": "uint128",
            "error": "none"
          }
        }
      }
    },
    {
      "name": "test-emit-event",
      "access": "public",
      "args": [],
      "outputs": {
        "type": {
          "response": {
            "ok": "uint128",
            "error": "none"
          }
        }
      }
    },
    {
      "name": "test-event-types",
      "access": "public",
      "args": [],
      "outputs": {
        "type": {
          "response": {
            "ok": "uint128",
            "error": "none"
          }
        }
      }
    }
  ],
  "variables": [
    {
      "name": "recipient",
      "type": "principal",
      "access": "constant"
    },
    {
      "name": "sender",
      "type": "principal",
      "access": "constant"
    }
  ],
  "maps": [
    {
      "name": "store",
      "key": [
        {
          "name": "key",
          "type": {
            "buffer": {
              "length": 32
            }
          }
        }
      ],
      "value": [
        {
          "name": "value",
          "type": {
            "buffer": {
              "length": 32
            }
          }
        }
      ]
    }
  ],
  "fungible_tokens": [
    {
      "name": "novel-token-19"
    }
  ],
  "non_fungible_tokens": [
    {
      "name": "hello-nft",
      "type": "uint128"
    }
  ]
}
