=== stacks-network/stacks-core/docs/rpc/api/core-node/post-fee-transaction-response.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "POST response for estimated fee",
  "title": "TransactionFeeEstimateResponse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "estimated_cost",
    "estimated_cost_scalar",
    "cost_scalar_change_by_byte",
    "estimations"
  ],
  "properties": {
    "estimated_cost_scalar": {
      "type": "integer"
    },
    "cost_scalar_change_by_byte": {
      "type": "number"
    },
    "estimated_cost": {
      "type": "object",
      "additionalProperties": false,
      "required": ["read_count", "write_count", "read_length", "write_length", "runtime"],
      "properties": {
        "read_count": { "type": "integer" },
        "read_length": { "type": "integer" },
        "runtime": { "type": "integer" },
        "write_count": { "type": "integer" },
        "write_length": { "type": "integer" }
      }
    },
    "estimations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "fee_rate": {
            "type": "number"
          },
          "fee": {
            "type": "number"
          }
        }
      }
    }
  }
}

=== stacks-network/stacks-core/docs/rpc/components/examples/fee-transaction-response.example.json
{
  "cost_scalar_change_by_byte": 0.00476837158203125,
  "estimated_cost": {
    "read_count": 19,
    "read_length": 4814,
    "runtime": 7175000,
    "write_count": 2,
    "write_length": 1020
  },
  "estimated_cost_scalar": 14,
  "estimations": [
    {
      "fee": 17,
      "fee_rate": 1.2410714285714286
    },
    {
      "fee": 125,
      "fee_rate": 8.958333333333332
    },
    {
      "fee": 140,
      "fee_rate": 10
    }
  ]
}
